use bili

db.doctors.insert({"username" : "jake", "password" : "password", "name" : "Jake Osselaer", "hospital": "Sacred Heart", "hospitalAddress": "123 E Fake st", "city": "Dallas, TX" })
db.doctors.insert({"username" : "arturo", "password" : "password", "name" : "Arturo Laguna", "hospital": "Mayo Clinic", "hospitalAddress": "234 E Mayo", "city": "Denton, TX" })
db.doctors.insert({"username" : "van", "password" : "password", "name" : "Van Tran", "hospital": "Baylor Hospital", "hospitalAddress": "876 W Baylor", "city": "Waco, TX" })
db.doctors.insert({"username" : "andrew", "password" : "password", "name" : "Andrew Watts", "hospital": "Private Practice", "hospitalAddress": "765 Dyer St", "city": "Irving, TX" })
db.doctors.insert({"username" : "alexis", "password" : "password", "name" : "Alexis Doe", "hospital": "Greys Anatomy", "hospitalAddress": "8932 N Grey Blvd", "city": "Fort Worth, TX" })
db.doctors.insert({"username" : "peter", "password" : "password", "name" : "Peter Griffin", "hospital": "Mayo Clinic", "hospitalAddress": "234 E Mayo", "city": "Denton, TX" })
db.doctors.insert({"username" : "julie", "password" : "password", "name" : "Juile Vander", "hospital": "Sacred Heart", "hospitalAddress": "123 E Fake st", "city": "Dallas, TX" })
db.doctors.insert({"username" : "hannah", "password" : "password", "name" : "Hannah Griffin", "hospital": "Baylor Hospital", "hospitalAddress": "876 W Baylor", "city": "Waco, TX" })
db.doctors.insert({"username" : "john", "password" : "password", "name" : "John Doe", "hospital": "Greys Anatomy", "hospitalAddress": "8932 N Grey Blvd", "city": "Fort Worth, TX" })
db.doctors.insert({"username" : "peter2", "password" : "password", "name" : "Peter Rabbit", "hospital": "Urgent Care", "hospitalAddress": "83894 Snider ave", "city": "Dallas, TX" })
db.doctors.insert({"username" : "john2", "password" : "password", "name" : "John alexander", "hospital": "Highland Park Emergency", "hospitalAddress": "123 E Fake st", "city": "Dallas, TX" })
db.doctors.insert({"username" : "james", "password" : "password", "name" : "James Doe", "hospital": "Sacred Heart", "hospitalAddress": "123 E Fake st", "city": "Dallas, TX" })
db.doctors.insert({"username" : "jane", "password" : "password", "name" : "Jane Doe", "hospital": "Baylor Hospital", "hospitalAddress": "876 W Baylor", "city": "Waco, TX" })
db.doctors.insert({"username" : "john3", "password" : "password", "name" : "John Doe", "hospital": "Greys Anatomy", "hospitalAddress": "8932 N Grey Blvd", "city": "Fort Worth, TX" })
